package com.capekdev.projekuts

object ProfileBank {
    var profiles: Array<Profile> = arrayOf(
        Profile(
            "Erich Pramana Muljadi", "NRP 160423046", "Program NCS",
            " About Me Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean felis justo, sollicitudin id purus sed, ullamcorper vestibulum diam. Duis porttitor risus nulla, vitae mollis justo venenatis ut. Morbi orci leo, sollicitudin vitae diam sit amet, sollicitudin condimentum arcu. Donec augue urna, vestibulum sed odio in, efficitur dictum nisi. Cras pretium justo arcu. Praesent ex velit, ullamcorper a tortor at, mollis interdum libero. Cras porttitor sit amet lacus eu euismod. Sed viverra, nunc at faucibus lobortis, ipsum lectus cursus tortor, nec congue purus felis eget metus. Cras euismod nulla metus, sed tincidunt diam tristique sed. Sed luctus finibus urna nec accumsan. Nullam nec turpis ut elit sollicitudin imperdiet eget eget quam.",
            "My Course Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean felis justo, sollicitudin id purus sed, ullamcorper vestibulum diam. Duis porttitor risus nulla, vitae mollis justo venenatis ut. Morbi orci leo, sollicitudin vitae diam sit amet, sollicitudin condimentum arcu. Donec augue urna, vestibulum sed odio in, efficitur dictum nisi. Cras pretium justo arcu. Praesent ex velit, ullamcorper a tortor at, mollis interdum libero. Cras porttitor sit amet lacus eu euismod. Sed viverra, nunc at faucibus lobortis, ipsum lectus cursus tortor, nec congue purus felis eget metus. Cras euismod nulla metus, sed tincidunt diam tristique sed. Sed luctus finibus urna nec accumsan. Nullam nec turpis ut elit sollicitudin imperdiet eget eget quam.",
            "My Experiences Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean felis justo, sollicitudin id purus sed, ullamcorper vestibulum diam. Duis porttitor risus nulla, vitae mollis justo venenatis ut. Morbi orci leo, sollicitudin vitae diam sit amet, sollicitudin condimentum arcu. Donec augue urna, vestibulum sed odio in, efficitur dictum nisi. Cras pretium justo arcu. Praesent ex velit, ullamcorper a tortor at, mollis interdum libero. Cras porttitor sit amet lacus eu euismod. Sed viverra, nunc at faucibus lobortis, ipsum lectus cursus tortor, nec congue purus felis eget metus. Cras euismod nulla metus, sed tincidunt diam tristique sed. Sed luctus finibus urna nec accumsan. Nullam nec turpis ut elit sollicitudin imperdiet eget eget quam.",
            R.drawable.erich
        ),
        Profile(
            "Nelson Ahli", "NRP 160423077", "Program DSAI",
            " About Me Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean felis justo, sollicitudin id purus sed, ullamcorper vestibulum diam. Duis porttitor risus nulla, vitae mollis justo venenatis ut. Morbi orci leo, sollicitudin vitae diam sit amet, sollicitudin condimentum arcu. Donec augue urna, vestibulum sed odio in, efficitur dictum nisi. Cras pretium justo arcu. Praesent ex velit, ullamcorper a tortor at, mollis interdum libero. Cras porttitor sit amet lacus eu euismod. Sed viverra, nunc at faucibus lobortis, ipsum lectus cursus tortor, nec congue purus felis eget metus. Cras euismod nulla metus, sed tincidunt diam tristique sed. Sed luctus finibus urna nec accumsan. Nullam nec turpis ut elit sollicitudin imperdiet eget eget quam.",
            "My Course Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean felis justo, sollicitudin id purus sed, ullamcorper vestibulum diam. Duis porttitor risus nulla, vitae mollis justo venenatis ut. Morbi orci leo, sollicitudin vitae diam sit amet, sollicitudin condimentum arcu. Donec augue urna, vestibulum sed odio in, efficitur dictum nisi. Cras pretium justo arcu. Praesent ex velit, ullamcorper a tortor at, mollis interdum libero. Cras porttitor sit amet lacus eu euismod. Sed viverra, nunc at faucibus lobortis, ipsum lectus cursus tortor, nec congue purus felis eget metus. Cras euismod nulla metus, sed tincidunt diam tristique sed. Sed luctus finibus urna nec accumsan. Nullam nec turpis ut elit sollicitudin imperdiet eget eget quam.",
            "My Experiences Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean felis justo, sollicitudin id purus sed, ullamcorper vestibulum diam. Duis porttitor risus nulla, vitae mollis justo venenatis ut. Morbi orci leo, sollicitudin vitae diam sit amet, sollicitudin condimentum arcu. Donec augue urna, vestibulum sed odio in, efficitur dictum nisi. Cras pretium justo arcu. Praesent ex velit, ullamcorper a tortor at, mollis interdum libero. Cras porttitor sit amet lacus eu euismod. Sed viverra, nunc at faucibus lobortis, ipsum lectus cursus tortor, nec congue purus felis eget metus. Cras euismod nulla metus, sed tincidunt diam tristique sed. Sed luctus finibus urna nec accumsan. Nullam nec turpis ut elit sollicitudin imperdiet eget eget quam.",
            R.drawable.nelson
        ),
        Profile(
            "Steven Gunawan", "NRP 160423085", "Program DSAI",
            " About Me Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean felis justo, sollicitudin id purus sed, ullamcorper vestibulum diam. Duis porttitor risus nulla, vitae mollis justo venenatis ut. Morbi orci leo, sollicitudin vitae diam sit amet, sollicitudin condimentum arcu. Donec augue urna, vestibulum sed odio in, efficitur dictum nisi. Cras pretium justo arcu. Praesent ex velit, ullamcorper a tortor at, mollis interdum libero. Cras porttitor sit amet lacus eu euismod. Sed viverra, nunc at faucibus lobortis, ipsum lectus cursus tortor, nec congue purus felis eget metus. Cras euismod nulla metus, sed tincidunt diam tristique sed. Sed luctus finibus urna nec accumsan. Nullam nec turpis ut elit sollicitudin imperdiet eget eget quam.",
            "My Course Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean felis justo, sollicitudin id purus sed, ullamcorper vestibulum diam. Duis porttitor risus nulla, vitae mollis justo venenatis ut. Morbi orci leo, sollicitudin vitae diam sit amet, sollicitudin condimentum arcu. Donec augue urna, vestibulum sed odio in, efficitur dictum nisi. Cras pretium justo arcu. Praesent ex velit, ullamcorper a tortor at, mollis interdum libero. Cras porttitor sit amet lacus eu euismod. Sed viverra, nunc at faucibus lobortis, ipsum lectus cursus tortor, nec congue purus felis eget metus. Cras euismod nulla metus, sed tincidunt diam tristique sed. Sed luctus finibus urna nec accumsan. Nullam nec turpis ut elit sollicitudin imperdiet eget eget quam.",
            "My Experiences Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean felis justo, sollicitudin id purus sed, ullamcorper vestibulum diam. Duis porttitor risus nulla, vitae mollis justo venenatis ut. Morbi orci leo, sollicitudin vitae diam sit amet, sollicitudin condimentum arcu. Donec augue urna, vestibulum sed odio in, efficitur dictum nisi. Cras pretium justo arcu. Praesent ex velit, ullamcorper a tortor at, mollis interdum libero. Cras porttitor sit amet lacus eu euismod. Sed viverra, nunc at faucibus lobortis, ipsum lectus cursus tortor, nec congue purus felis eget metus. Cras euismod nulla metus, sed tincidunt diam tristique sed. Sed luctus finibus urna nec accumsan. Nullam nec turpis ut elit sollicitudin imperdiet eget eget quam.",
            R.drawable.steven
        )
    )
}